### ISSUE TITLE
关于构造函数参数

### ISSUE THREAD

**Issue by Cobalt-27** [YeeTone/DI-OOAD-22Fall-public#11]
> If @Value is marked on parameters in constructor, when execute the constructor, an specific value should be given to corresponding parameters. We ensure that, in our test cases, all parameters in the constructor that annotated by @Inject are either injected or annotated by @Value. If the value() String appears in the value.properties, then first replace it as defined in the properties file; Otherwise, use itself as value().

但是@Inject好像没法作用于parameter

**Comment by YeeTone** [comment]
> > If @value is marked on parameters in constructor, when execute the constructor, an specific value should be given to corresponding parameters. We ensure that, in our test cases, all parameters in the constructor that annotated by @Inject are either injected or annotated by @value. If the value() String appears in the value.properties, then first replace it as defined in the properties file; Otherwise, use itself as value().
> 
> 但是@Inject好像没法作用于parameter

我不是很明白你的问题点。题面中并未做出任何constructor的parameter会被`@Inject`修饰的说明。

**Comment by Cobalt-27** [comment]
> We ensure that, in our test cases, all parameters in the constructor that annotated by @Inject are either injected or annotated by @value.

@YeeTone 

对题面这一句有点疑问，我的理解是`all parameters are either injected or annotated`。

**Comment by YeeTone** [comment]
对，将那句话简化后就是all parameters are injected or annotated by `@Value`。

**Comment by Cobalt-27** [comment]
> 

请问这里要表达的意思是：所有的parameter都一定会被@value修饰吗。

**Comment by Cobalt-27** [comment]
> > 
> 
> 请问这里要表达的意思是：所有的parameter都一定会被@value修饰吗。

（指定的constructor的parameter都一定会被@value修饰。

**Comment by YeeTone** [comment]
如果构造方法里面的参数是value规定修饰的那9种类型，那么一定会被value注解修饰。

**Comment by Cobalt-27** [comment]
> 如果构造方法里面的参数是value规定修饰的那9种类型，那么一定会被value注解修饰。

好的，感谢。我好像明白了，之前理解的有点偏差。
