### ISSUE TITLE
是否会出现同一个类的同一个成员被注入两次的情况

### ISSUE THREAD

**Issue by Trust04zh** [YeeTone/DI-OOAD-22Fall-public#5]
下面的例子里两处`@Inject`均要求注入`a`，请问会存在这样的情况吗？我没有找到对这种情况的说明，如果已经有了烦请指出。

```java
public class AB2 {
    @Inject
    private A a;
    private B b;

    @Inject
    public AB2(A a, B b){
        this.a = a;
        this.b = b;
    }
}
```

**Comment by YeeTone** [comment]
这是一个非常好的问题。

由于AB2类的成员变量和构造方法都有`@Inject`修饰，因此这样的情形应当会被考虑为注入两次，但实际上与仅保留其中一个`@Inject`注解的注入效果是一样的。

**Comment by YeeTone** [comment]
> 确实，上面的例子没举好，两处`@inject`的行为是一致的，下面这个例子呢
> 
> ```
> public class AB2 {
>     @Value(value = "1")
>     private int a;
> 
>     @Inject
>     public AB2(@value(value = "2") int a){
>         this.a = a;
>     }
> }
> ```

在标准实现中，由于需要先调用构造方法来实例化对象，然后再设置里面的成员变量，因此先注入value为"2"的a，然后注入value为"1"的a。

但考虑这样的注入方式存在二义性，我们保证official test中不会有这种在多个地方注入的情况。
