### ISSUE TITLE
是否可以支持kotlin

### ISSUE THREAD

**Issue by 2catycm** [YeeTone/DI-OOAD-22Fall-public#6]
kotlin是jvm家族的一员，和Java互操作性较好，且有更现代的性质，不知道OJ是否支持呢？

**Comment by YeeTone** [comment]
目前oj测评环境暂未支持kt。

如果你使用了kt来编写本次作业，那你可以在sakai上提交后，在qq私戳我（告诉我你已经在sakai上提交了）进行手工批改，我会及时处理使用kt语言的提交。

**Comment by 2catycm** [comment]
好的，谢谢
