### ISSUE TITLE
关于@Value中的括号的问题

### ISSUE THREAD

**Issue by Yan-ice** [YeeTone/DI-OOAD-22Fall-public#9]
原则上，对于数组或集合类型，序列化的字符串一定带有括号（DI作业文档里也带了），相反，如果带了括号，那一定代表着数组或集合。
在这个前提下，显然合法的注入：
```
@Value(value= "[1,2,3]")
int[] value_set;

@Value(value= "1,2,3")
int single_value;
```

**但是，在本次DI作业中，以下注入的结果如何呢？**
```
@Value(value= "1,2,3")
int[] value_set;
```
对于以上代码，我的理解：由于三个元素均为int，而没有int[]，**因此没有合法输入，最终value_set为null。**

```
@Value(value= "[1,2,3]")
int single_value;
```
对于以上代码，我的理解：只有一个元素int[]，没有int，**因此没有合法输入，最终single_value为默认值0。**

顺便，虽然official test应该不考，但是也可以考虑的混合情况：
```
@Value(value= "[1,2,3],4")
int single_value;
```
对于以上代码，我的理解：第一个元素为int[], 第二个元素为int, single_value的值应该为4.

不知道这样的理解是否正确呐。

**Comment by YeeTone** [comment]
这个问题似乎在之前的issue中有出现：）

我将会对这个issue中的各个情况做逐一的说明。

(1) int[]的注入值中两侧没有括号修饰符。
```java
@Value(value= "1,2,3")
int[] value_set;
```

这个问题我们在[Issue#3](https://github.com/YeeTone/DI-OOAD-22Fall-public/issues/3)中有进行过讨论，数组或容器一定会包含两侧的括号，因此不需要考虑这种情况。

(2) int的注入值中有两侧的括号。
```java
@Value(value= "[1,2,3]")
int single_value;
```

这个问题也是在[Issue#3](https://github.com/YeeTone/DI-OOAD-22Fall-public/issues/3)中有过讨论的。

这种情况先应用delimiter()进行分割，得到一个长度为3的String[] array。array[0]=`"[1"`，array[1]=`"2"`，array[2]=`"3]"`。其中array[0]和array[2]都不是int的合法表示形式，因此我们忽略。array[1]是第一个符合的表示形式，因此就应用array[1]进行注入，得到的结果是2。

(3) int的注入值中有混合括号。

这种情况和(2)是类似的，得到的String[]是`["[1", "2", "3]", "4"]`。array[1]是第一个符合的表示形式，因此使用`"2"`进行注入。
